import { X, Printer } from "lucide-react";
import { useApp } from "../contexts/AppContext";
import { formatCurrency, formatDate } from "../utils/helpers";

export const InvoiceModal = ({ onClose, transaction }) => {
  const { store, selectedCustomer } = useApp();
  
  if (!transaction || !selectedCustomer) return null;

  const handlePrint = () => window.print();

  return (
    <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 print:bg-white print:static print:p-0">
      <div className="bg-white dark:bg-gray-800 rounded-2xl max-w-md w-full max-h-[90vh] overflow-y-auto print:max-w-none print:rounded-none print:shadow-none">
        {/* Screen-only header */}
        <div className="flex justify-between items-center p-4 border-b border-gray-200 print:hidden">
          <h3 className="font-bold text-lg text-gray-900 dark:text-white">Invoice</h3>
          <div className="flex gap-2">
            <button onClick={handlePrint} className="p-2 bg-green-700 text-white rounded-lg active:scale-95 transition">
              <Printer size={18} />
            </button>
            <button onClick={onClose} className="p-2 bg-gray-200 dark:bg-gray-700 rounded-lg active:scale-95 transition">
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Printable content */}
        <div className="p-6 print:p-8 text-gray-900">
          {/* Store header */}
          <div className="text-center border-b-2 border-green-700 pb-4 mb-4">
            <div className="w-16 h-16 bg-green-700 rounded-full mx-auto mb-2 flex items-center justify-center text-yellow-400 font-bold text-2xl">
              {store.name.charAt(0)}
            </div>
            <h2 className="text-xl font-bold">{store.name}</h2>
            <p className="text-sm text-gray-600">{store.phone}</p>
          </div>

          {/* Invoice info */}
          <div className="flex justify-between mb-6 text-sm">
            <div>
              <p className="font-bold">Bill To:</p>
              <p>{selectedCustomer.name}</p>
              <p className="text-gray-600">{selectedCustomer.phone}</p>
            </div>
            <div className="text-right">
              <p className="font-bold">Invoice #{transaction.id.slice(0, 6).toUpperCase()}</p>
              <p className="text-gray-600">{formatDate(transaction.date)}</p>
            </div>
          </div>

          {/* Items */}
          <table className="w-full mb-6">
            <thead>
              <tr className="border-b-2 border-gray-200">
                <th className="text-left py-2 text-sm">Description</th>
                <th className="text-right py-2 text-sm">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-100">
                <td className="py-3">{transaction.items || "General Purchase"}</td>
                <td className="text-right font-semibold">{formatCurrency(transaction.amount)}</td>
              </tr>
            </tbody>
          </table>

          {/* Totals */}
          <div className="space-y-2 border-t border-gray-200 pt-4">
            <div className="flex justify-between text-sm">
              <span className="text-gray-600">Previous Balance:</span>
              <span className="font-semibold">{formatCurrency(transaction.prevBalance)}</span>
            </div>
            <div className="flex justify-between text-sm">
              <span className="text-gray-600">New Purchase:</span>
              <span className="font-semibold">{formatCurrency(transaction.amount)}</span>
            </div>
            <div className="flex justify-between text-sm text-green-700">
              <span>Amount Paid:</span>
              <span className="font-semibold">- {formatCurrency(transaction.paid)}</span>
            </div>
            <div className="flex justify-between text-lg font-bold border-t border-gray-200 pt-2 mt-2">
              <span>New Balance:</span>
              <span className={transaction.newBalance > 0 ? "text-red-600" : transaction.newBalance < 0 ? "text-blue-600" : "text-green-600"}>
                {transaction.newBalance < 0 ? `Credit: ${formatCurrency(Math.abs(transaction.newBalance))}` : formatCurrency(transaction.newBalance)}
              </span>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-8 text-center text-xs text-gray-500 border-t border-gray-200 pt-4">
            <p>Thank you for your business!</p>
            <p className="mt-1">Generated by CreditBook</p>
          </div>
        </div>
      </div>

      {/* Print-specific styles */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .print\\:bg-white, .print\\:bg-white * { visibility: visible; }
          .print\\:bg-white { position: absolute; left: 0; top: 0; width: 100%; }
        }
      `}</style>
    </div>
  );
};